Use SMB Copy and fall back to WinRM for copy file from/to remote comp…
microsoft/SdnDiagnostics pull request #75
Opened 2021-09-29 03:46 UTC by luyaof

# Description
Summary of changes:
- Copy-FileFromPSRemoteSession and Copy-FileToPSRemoteSession to use SMB first and fallback to WinRM if SMB failed

# Change type
- [ ] Bug fix (non-breaking change)
- [ ] Code style update (formatting, local variables)
- [x] New Feature (non-breaking change that adds new functionality without impacting existing)
- [ ] Breaking change (fix or feature that may cause functionality impact)
- [ ] Other

# Checklist:
- [x] My code follows the style and contribution guidelines of this project.
- [x] I have tested and validated my code changes.

2021-09-29 16:20 UTC, arudell requested changes
We should move this SMB copy function to its own function and then create a wrapper function over SMB copy and WinRM copy functions. That way we have redundancy and granularity.

2021-10-01 14:39 UTC, arudell requested changes

2021-10-04 02:34 UTC, luyaof commented on src/modules/Utilities/private/Copy-FileFromRemoteComputer.ps1
>              }
Added the exception handling of WinRM Copy. Failure for one computer should not stop the other, the behavior like below in last change. Example of both SMB and WinRM blocked for one of the machine.
```
WARNING: Unable to create powershell session to sdnexpNC01
 System.Management.Automation.Remoting.PSRemotingTransportException: Connecting to remote server sdnexpNC01 failed with the following error message : The client cannot connect to the destination specified in the request. Verify that the service on the destination is running and is accepting requests. Consult the logs and documentation for the WS-Management service running on the destination, most commonly IIS or WinRM. If the destination is the WinRM service, run the
following command on the destination to analyze and configure the WinRM service: "winrm quickconfig". For more information, see the about_Remote_Troubleshooting Help topic.
Copying files from \\sdnexpNC02\C$\Windows\Tracing\SDNDiagnostics\NetworkControllerState\*
Copying files from \\sdnexpNC01\C$\Windows\Tracing\SDNDiagnostics\NetworkControllerState\*
SMB Copy failed, fallback to WinRM
WARNING: Unable to create powershell session to sdnexpNC01
 System.Management.Automation.Remoting.PSRemotingTransportException: Connecting to remote server sdnexpNC01 failed with the following error message : The client cannot connect to the destination specified in the request. Verify that the service on the destination is running and is accepting requests. Consult the logs and documentation for the WS-Management service running on the destination, most commonly IIS or WinRM. If the destination is the WinRM service, run the
following command on the destination to analyze and configure the WinRM service: "winrm quickconfig". For more information, see the about_Remote_Troubleshooting Help topic.
WARNING: Unable to copy files from sdnexpNC01 as no remote session could be established
WinRM Copy failed
Copying files from \\sdnexpNC03\C$\Windows\Tracing\SDNDiagnostics\NetworkControllerState\*
```

2021-10-04 13:23 UTC, arudell approved these changes

2021-10-04 13:24 UTC, merged